# Aura SDLC Local Docker Debugging Configuration
# Enhanced version with debugging capabilities, logging, and monitoring

version: '3.8'

services:
  # MariaDB Database Service with Enhanced Logging
  aura-database:
    build:
      context: ../../
      dockerfile: containers/database/Dockerfile
    container_name: aura-database-debug
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: aura_root_password_123
      MYSQL_DATABASE: aura_playground
      MYSQL_USER: aura_user
      MYSQL_PASSWORD: aura_password_123
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    volumes:
      - aura-db-data:/var/lib/mysql
      - ../../config/database/my.ini:/etc/mysql/conf.d/custom.cnf:ro
      # Database logs for debugging
      - ./logs/database:/var/log/mysql
    networks:
      - aura-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "aura_user", "-paura_password_123"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # MCP Services with Debug Logging
  aura-mcp-services:
    build:
      context: ../../
      dockerfile: containers/mcp-services/Dockerfile
    container_name: aura-mcp-services-debug
    restart: unless-stopped
    environment:
      # MCP Configuration
      MCP_BRIDGE_PORT: 8000
      PLAYWRIGHT_MCP_PORT: 8931
      PLAYWRIGHT_HEADLESS: "true"
      DISPLAY: ":99"
      PYTHONUNBUFFERED: 1
      
      # Enhanced debugging
      LOG_LEVEL: DEBUG
      DEBUG: "true"
      VERBOSE: "true"
    ports:
      - "8000:8000"   # Python MCP Server
      - "8931:8931"   # Playwright MCP Server
      - "8932:8932"   # Reserved for future Jira MCP
    volumes:
      - ../../mcp/screenshots:/app/screenshots
      - ../../mcp/.env:/app/.env:ro
      # Debug logs volume
      - ./logs/mcp:/app/logs
    networks:
      - aura-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - aura-database

  # Aura Application with Debug Mode
  aura-application:
    build:
      context: ../../
      dockerfile: containers/application/Dockerfile.debug
    container_name: aura-application-debug
    restart: unless-stopped
    environment:
      # Application configuration
      NODE_ENV: development
      PORT: 3000
      
      # Enhanced debugging
      DEBUG: "*"
      VERBOSE: "true"
      LOG_LEVEL: debug
      
      # Database configuration
      AURA_DB_HOST: aura-database-debug
      AURA_DB_PORT: 3306
      AURA_DB_USER: aura_user
      AURA_DB_PASSWORD: aura_password_123
      AURA_DB_NAME: aura_playground
      AURA_DB_SSL: "false"
      
      # MCP configuration
      MCP_BRIDGE_URL: http://aura-mcp-services-debug:8000
      PLAYWRIGHT_MCP_URL: http://aura-mcp-services-debug:8931
      
      # LLM API configuration with debug logging
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      
      # Enable LLM request/response logging
      LLM_DEBUG: "true"
      LLM_LOG_REQUESTS: "true"
      LLM_LOG_RESPONSES: "true"
      
      # Application URLs
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - "3000:3000"
      - "9229:9229"   # Node.js debugging port
    volumes:
      # Application logs
      - ./logs/application:/app/logs
      # Source code mapping for debugging (optional)
      - ../../src:/app/src
    networks:
      - aura-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/database/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - aura-database
      - aura-mcp-services

  # Log aggregation service (optional but recommended)
  log-viewer:
    image: amir20/dozzle:latest
    container_name: aura-log-viewer
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aura-network
    environment:
      DOZZLE_LEVEL: debug
      DOZZLE_TAILSIZE: 300

# Networks
networks:
  aura-network:
    driver: bridge
    name: aura-network-debug

# Volumes
volumes:
  aura-db-data:
    driver: local
    name: aura-db-data-debug







